version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: un_security
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # You don't need to expose 5432 unless your host needs to connect directly:
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 12

  redis:
    image: redis:7-alpine
    # No need to expose unless host connects directly:
    # ports:
    #   - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      # Django
      - DEBUG=1
      - SECRET_KEY=supersecret
      - ALLOWED_HOSTS=*
      # DB params read by decouple in settings.py
      - DB_NAME=un_security
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      # You can keep DATABASE_URL or remove it. It won’t be used unless you parse it.
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/un_security

volumes:
  postgres_data:
