"""
Django settings for un_security_system project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
from decouple import config
import os
from dotenv import load_dotenv


# ---------------------------------------------------------------------
# BASE DIRECTORY
# ---------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file from project root
load_dotenv(BASE_DIR / ".env")


# ---------------------------------------------------------------------
# SECURITY
# ---------------------------------------------------------------------

# Keep this for now so the current installation continues working.
# Recommended: move SECRET_KEY to .env.prod and rotate it later.
SECRET_KEY = 'django-insecure-wouhxk0li%q9hdy#d$)@ldsz#=36dfj)$%$*=r_wnosa!o-@a*'

# Never enable DEBUG on production.
DEBUG = False

ALLOWED_HOSTS = [
    "unpass.gm",
    "www.unpass.gm",
    "localhost",
    "127.0.0.1",
]

# Required because production is accessed over HTTPS.
CSRF_TRUSTED_ORIGINS = [
    "https://unpass.gm",
    "https://www.unpass.gm",
]

# Nginx terminates HTTPS and proxies requests to Django.
SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)

# Secure cookies in production.
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

SESSION_COOKIE_HTTPONLY = True

CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"


# ---------------------------------------------------------------------
# APPLICATIONS
# ---------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'channels',
    'rest_framework',
    'corsheaders',
    'crispy_forms',
    'crispy_bootstrap5',

    'accounts',
    'tenancy',
    'vehicles',
    'visitors',
    'incidents',
    'comms',
    'dashboard',
]


# ---------------------------------------------------------------------
# MIDDLEWARE
# ---------------------------------------------------------------------

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'accounts.middleware.ForcePasswordChangeMiddleware',
    'tenancy.middleware.FeatureGateMiddleware',
]


# ---------------------------------------------------------------------
# URL / ASGI / WSGI
# ---------------------------------------------------------------------

ROOT_URLCONF = 'un_security_system.urls'

WSGI_APPLICATION = 'un_security_system.wsgi.application'
ASGI_APPLICATION = 'un_security_system.asgi.application'


# ---------------------------------------------------------------------
# TEMPLATES
# ---------------------------------------------------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / 'templates',
        ],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'accounts.context_processors.agency_service_flags',
                'tenancy.context_processors.tenancy',
                'accounts.context_processors_esign.esign_badge',
            ],
        },
    },
]


# ---------------------------------------------------------------------
# DATABASE
# ---------------------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',

        'NAME': config(
            'DB_NAME',
            default='un_security',
        ),

        'USER': config(
            'DB_USER',
            default='postgres',
        ),

        'PASSWORD': config(
            'DB_PASSWORD',
            default='postgres',
        ),

        'HOST': config(
            'DB_HOST',
            default='db',
        ),

        'PORT': config(
            'DB_PORT',
            default='5432',
        ),
    }
}


# ---------------------------------------------------------------------
# CHANNELS / REDIS
# ---------------------------------------------------------------------

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',

        'CONFIG': {
            'hosts': [
                ('redis', 6379),
            ],
        },
    },
}


# ---------------------------------------------------------------------
# PASSWORD VALIDATION
# ---------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]


# ---------------------------------------------------------------------
# INTERNATIONALIZATION
# ---------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Banjul'

USE_I18N = True
USE_TZ = True


# ---------------------------------------------------------------------
# STATIC FILES
# ---------------------------------------------------------------------

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# ---------------------------------------------------------------------
# MEDIA FILES
# ---------------------------------------------------------------------

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# ---------------------------------------------------------------------
# CRISPY FORMS
# ---------------------------------------------------------------------

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"


# ---------------------------------------------------------------------
# DEFAULT PRIMARY KEY
# ---------------------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ---------------------------------------------------------------------
# CUSTOM USER MODEL
# ---------------------------------------------------------------------

AUTH_USER_MODEL = 'accounts.User'


# ---------------------------------------------------------------------
# LOGIN / LOGOUT
# ---------------------------------------------------------------------

LOGIN_URL = '/accounts/login/'

LOGIN_REDIRECT_URL = '/dashboard/'

LOGOUT_REDIRECT_URL = '/accounts/login/'


# ---------------------------------------------------------------------
# REST FRAMEWORK
# ---------------------------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


# ---------------------------------------------------------------------
# EMAIL
# ---------------------------------------------------------------------

EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)

EMAIL_HOST = os.getenv(
    "EMAIL_HOST",
    "smtp.office365.com",
)

EMAIL_PORT = int(
    os.getenv(
        "EMAIL_PORT",
        587,
    )
)

EMAIL_USE_TLS = (
    os.getenv(
        "EMAIL_USE_TLS",
        "True",
    ) == "True"
)

EMAIL_HOST_USER = os.getenv(
    "EMAIL_HOST_USER",
    "",
)

EMAIL_HOST_PASSWORD = os.getenv(
    "EMAIL_HOST_PASSWORD",
    "",
)

DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    EMAIL_HOST_USER,
)


# ---------------------------------------------------------------------
# ESIGN — OFFICE TO PDF
# ---------------------------------------------------------------------

ESIGN_SOFFICE_BIN = "soffice"

ESIGN_CONVERT_TIMEOUT = 120


# ---------------------------------------------------------------------
# ESIGN — COMPLETION EMAIL ATTACHMENTS
# ---------------------------------------------------------------------

ESIGN_ATTACH_COMPLETED = True

ESIGN_ATTACH_CERTIFICATE = True

ESIGN_ATTACH_MAX_BYTES = 10 * 1024 * 1024


# ---------------------------------------------------------------------
# ESIGN — BRANDING
# ---------------------------------------------------------------------

ESIGN_BRAND = "UNDP eSign"


# ---------------------------------------------------------------------
# ESIGN — SIGNATURE TRANSPARENCY
# ---------------------------------------------------------------------

# At or above this brightness -> transparent
ESIGN_SIGNATURE_CUT = 232

# At or below this brightness -> opaque
ESIGN_SIGNATURE_KEEP = 150


# ---------------------------------------------------------------------
# ESIGN STUDIO
# ---------------------------------------------------------------------

# Versions kept per workbench file
ESIGN_STUDIO_MAX_VERSIONS = 15

# Delete workbench files untouched this long.
# 0 means keep indefinitely.
ESIGN_STUDIO_RETENTION_DAYS = 90

# Remind a pending workflow step after this many days.
# 0 disables reminders.
ESIGN_WF_REMINDER_DAYS = 3


# ---------------------------------------------------------------------
# ESIGN PDF FONTS
# ---------------------------------------------------------------------

ESIGN_PDF_FONT_REGULAR = (
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
)

ESIGN_PDF_FONT_BOLD = (
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
)