# Generated by Django 4.2.7 on 2025-09-22 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorlog',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='visitorlog',
            name='visitor',
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
        migrations.DeleteModel(
            name='VisitorLog',
        ),
    ]
